// <auto-generated />
using System;
using LibPro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibPro.Migrations
{
    [DbContext(typeof(LibproContext))]
    [Migration("20260214150738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibPro.Models.Announcements", b =>
                {
                    b.Property<string>("AnnID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnnID");

                    b.HasIndex("Creator");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("LibPro.Models.Biblios", b =>
                {
                    b.Property<long>("BibID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BibID"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CatID")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryCatID")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PubDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PubID")
                        .HasColumnType("bigint");

                    b.Property<long?>("PublisherPubID")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BibID");

                    b.HasIndex("CategoryCatID");

                    b.HasIndex("PublisherPubID");

                    b.ToTable("Biblios");
                });

            modelBuilder.Entity("LibPro.Models.BookItems", b =>
                {
                    b.Property<string>("ItemID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("BibID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BiblioBibID")
                        .HasColumnType("bigint");

                    b.Property<byte?>("ItemStatusStatusCode")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ItmStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("LocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemID");

                    b.HasIndex("BiblioBibID");

                    b.HasIndex("ItemStatusStatusCode");

                    b.HasIndex("LocID");

                    b.ToTable("BookItems");
                });

            modelBuilder.Entity("LibPro.Models.Categories", b =>
                {
                    b.Property<int>("CatID")
                        .HasColumnType("int");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CatID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LibPro.Models.Cities", b =>
                {
                    b.Property<byte>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("LibPro.Models.Departments", b =>
                {
                    b.Property<string>("DeptID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DeptID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("LibPro.Models.FineTypes", b =>
                {
                    b.Property<byte>("FTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("FTID"));

                    b.Property<string>("FTName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(8)
                        .HasColumnType("decimal(8,0)");

                    b.HasKey("FTID");

                    b.ToTable("FineTypes");
                });

            modelBuilder.Entity("LibPro.Models.Fines", b =>
                {
                    b.Property<string>("FineID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("FTID")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("FineTypeFTID")
                        .HasColumnType("tinyint");

                    b.Property<bool>("ISPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LoanID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FineID");

                    b.HasIndex("FineTypeFTID");

                    b.HasIndex("LoanID");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("LibPro.Models.ItemStatus", b =>
                {
                    b.Property<byte>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("StatusCode"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusCode");

                    b.ToTable("ItemStatus");
                });

            modelBuilder.Entity("LibPro.Models.Loans", b =>
                {
                    b.Property<string>("LoanID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookItemItemID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PatronID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("RenewalCount")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LoanID");

                    b.HasIndex("BookItemItemID");

                    b.HasIndex("PatronID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibPro.Models.Locations", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<byte>("Depth")
                        .HasColumnType("tinyint");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.HasIndex("ParentID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("LibPro.Models.Patrons", b =>
                {
                    b.Property<string>("PatronID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CityID")
                        .HasColumnType("tinyint");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Memo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("PtrStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserAccountUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("PatronID");

                    b.HasIndex("CityID");

                    b.HasIndex("PtrStatus");

                    b.HasIndex("UserAccountUserID");

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("LibPro.Models.PatronsStatus", b =>
                {
                    b.Property<byte>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("StatusCode"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusCode");

                    b.ToTable("PatronsStatus");
                });

            modelBuilder.Entity("LibPro.Models.Publishers", b =>
                {
                    b.Property<long>("PubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PubID"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("CityID")
                        .HasColumnType("tinyint");

                    b.Property<string>("PubName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pubtel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PubID");

                    b.HasIndex("CityID");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("LibPro.Models.ReserveStatus", b =>
                {
                    b.Property<byte>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("StatusCode"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusCode");

                    b.ToTable("ReserveStatus");
                });

            modelBuilder.Entity("LibPro.Models.Reserves", b =>
                {
                    b.Property<string>("ResID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookItemItemID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatronID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ResStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("ResID");

                    b.HasIndex("BookItemItemID");

                    b.HasIndex("PatronID");

                    b.HasIndex("ResStatus");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("LibPro.Models.Reviews", b =>
                {
                    b.Property<long>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewID"));

                    b.Property<long>("BibID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BibliosBibID")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PatronID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RevStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReviewID");

                    b.HasIndex("BibliosBibID");

                    b.HasIndex("PatronID");

                    b.HasIndex("RevStatus");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LibPro.Models.Staff", b =>
                {
                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CityID")
                        .HasColumnType("tinyint");

                    b.Property<string>("DepartmentDeptID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAccountUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("StaffID");

                    b.HasIndex("CityID");

                    b.HasIndex("DepartmentDeptID");

                    b.HasIndex("UserAccountUserID");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("LibPro.Models.SystemStatus", b =>
                {
                    b.Property<byte>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("StatusCode"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusCode");

                    b.ToTable("SystemStatus");
                });

            modelBuilder.Entity("LibPro.Models.UserAccounts", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("UserType")
                        .HasColumnType("tinyint");

                    b.HasKey("UserID");

                    b.HasIndex("UserType");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("LibPro.Models.UserRoles", b =>
                {
                    b.Property<byte>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LibPro.Models.Announcements", b =>
                {
                    b.HasOne("LibPro.Models.Staff", "Staff")
                        .WithMany("Announcements")
                        .HasForeignKey("Creator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LibPro.Models.Biblios", b =>
                {
                    b.HasOne("LibPro.Models.Categories", "Category")
                        .WithMany("Biblios")
                        .HasForeignKey("CategoryCatID");

                    b.HasOne("LibPro.Models.Publishers", "Publisher")
                        .WithMany("Biblios")
                        .HasForeignKey("PublisherPubID");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibPro.Models.BookItems", b =>
                {
                    b.HasOne("LibPro.Models.Biblios", "Biblio")
                        .WithMany("BookItems")
                        .HasForeignKey("BiblioBibID");

                    b.HasOne("LibPro.Models.ItemStatus", "ItemStatus")
                        .WithMany("BookItems")
                        .HasForeignKey("ItemStatusStatusCode");

                    b.HasOne("LibPro.Models.Locations", "Location")
                        .WithMany("BookItems")
                        .HasForeignKey("LocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biblio");

                    b.Navigation("ItemStatus");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LibPro.Models.Fines", b =>
                {
                    b.HasOne("LibPro.Models.FineTypes", "FineType")
                        .WithMany("Fines")
                        .HasForeignKey("FineTypeFTID");

                    b.HasOne("LibPro.Models.Loans", "Loan")
                        .WithMany("Fines")
                        .HasForeignKey("LoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FineType");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LibPro.Models.Loans", b =>
                {
                    b.HasOne("LibPro.Models.BookItems", "BookItem")
                        .WithMany("Loans")
                        .HasForeignKey("BookItemItemID");

                    b.HasOne("LibPro.Models.Patrons", "Patron")
                        .WithMany("Loans")
                        .HasForeignKey("PatronID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookItem");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("LibPro.Models.Locations", b =>
                {
                    b.HasOne("LibPro.Models.Locations", "ParentLocation")
                        .WithMany("SubLocations")
                        .HasForeignKey("ParentID");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("LibPro.Models.Patrons", b =>
                {
                    b.HasOne("LibPro.Models.Cities", "City")
                        .WithMany("Patrons")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibPro.Models.PatronsStatus", "PatronsStatus")
                        .WithMany("Patrons")
                        .HasForeignKey("PtrStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibPro.Models.UserAccounts", "UserAccount")
                        .WithMany("Patrons")
                        .HasForeignKey("UserAccountUserID");

                    b.Navigation("City");

                    b.Navigation("PatronsStatus");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("LibPro.Models.Publishers", b =>
                {
                    b.HasOne("LibPro.Models.Cities", "City")
                        .WithMany("Publishers")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("LibPro.Models.Reserves", b =>
                {
                    b.HasOne("LibPro.Models.BookItems", "BookItem")
                        .WithMany("Reserves")
                        .HasForeignKey("BookItemItemID");

                    b.HasOne("LibPro.Models.Patrons", "Patron")
                        .WithMany("Reserves")
                        .HasForeignKey("PatronID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibPro.Models.ReserveStatus", "ReserveStatus")
                        .WithMany("Reserves")
                        .HasForeignKey("ResStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookItem");

                    b.Navigation("Patron");

                    b.Navigation("ReserveStatus");
                });

            modelBuilder.Entity("LibPro.Models.Reviews", b =>
                {
                    b.HasOne("LibPro.Models.Biblios", null)
                        .WithMany("Reviews")
                        .HasForeignKey("BibliosBibID");

                    b.HasOne("LibPro.Models.Patrons", "Patron")
                        .WithMany("Reviews")
                        .HasForeignKey("PatronID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibPro.Models.SystemStatus", "SystemStatus")
                        .WithMany("Reviews")
                        .HasForeignKey("RevStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patron");

                    b.Navigation("SystemStatus");
                });

            modelBuilder.Entity("LibPro.Models.Staff", b =>
                {
                    b.HasOne("LibPro.Models.Cities", "City")
                        .WithMany("Staffs")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibPro.Models.Departments", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentDeptID");

                    b.HasOne("LibPro.Models.UserAccounts", "UserAccount")
                        .WithMany("Staffs")
                        .HasForeignKey("UserAccountUserID");

                    b.Navigation("City");

                    b.Navigation("Department");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("LibPro.Models.UserAccounts", b =>
                {
                    b.HasOne("LibPro.Models.UserRoles", "UserRole")
                        .WithMany("UserAccounts")
                        .HasForeignKey("UserType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("LibPro.Models.Biblios", b =>
                {
                    b.Navigation("BookItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LibPro.Models.BookItems", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("LibPro.Models.Categories", b =>
                {
                    b.Navigation("Biblios");
                });

            modelBuilder.Entity("LibPro.Models.Cities", b =>
                {
                    b.Navigation("Patrons");

                    b.Navigation("Publishers");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("LibPro.Models.Departments", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("LibPro.Models.FineTypes", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibPro.Models.ItemStatus", b =>
                {
                    b.Navigation("BookItems");
                });

            modelBuilder.Entity("LibPro.Models.Loans", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibPro.Models.Locations", b =>
                {
                    b.Navigation("BookItems");

                    b.Navigation("SubLocations");
                });

            modelBuilder.Entity("LibPro.Models.Patrons", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reserves");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LibPro.Models.PatronsStatus", b =>
                {
                    b.Navigation("Patrons");
                });

            modelBuilder.Entity("LibPro.Models.Publishers", b =>
                {
                    b.Navigation("Biblios");
                });

            modelBuilder.Entity("LibPro.Models.ReserveStatus", b =>
                {
                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("LibPro.Models.Staff", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("LibPro.Models.SystemStatus", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LibPro.Models.UserAccounts", b =>
                {
                    b.Navigation("Patrons");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("LibPro.Models.UserRoles", b =>
                {
                    b.Navigation("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
